### ISSUE TITLE
map is not displayed in the preview

### ISSUE THREAD

**Issue by eduard-k** [amdecker/obsidian-argdown-plugin#1]
Hi,

After installing the plugin, syntax highlighting. But the map is not displayed in the preview. Mermaid works in preview mode.
Perhaps I need to specify the path for argdown/cli with `argdown --config`? 

<img width="916" alt="CleanShot 2021-06-27 at 12 28 19@2x" src="https://user-images.githubusercontent.com/7514378/123539603-38c2c000-d743-11eb-8221-caf1fb0e1c1e.png">

**Comment by amdecker** [comment]
When you first start up, it takes a few seconds before loading everything to make sure that every page gets rendered properly.

But if it stays unrendered like that for a while, check the console for any errors (ctrl shift i). Do you see any errors in the console?

**Comment by eduard-k** [comment]
> Do you see any errors in the console?

```
Uncaught (in promise) TypeError: command.replaceAll is not a function
    at sanitize (eval at <anonymous> (app.js:1), <anonymous>:102:20)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:40:82)
    at Generator.next (<anonymous>)
    at fulfilled (eval at <anonymous> (app.js:1), <anonymous>:24:58)
```

As I understand it, the error is in line 90:
`return command.replaceAll(/[ !"#$&'()*;<>?\[\\`{|~\t\n]/g, (match:string) => {`

**Comment by amdecker** [comment]
I updated, let me know if there is anything else.

**Comment by eduard-k** [comment]
It works, thanks
