### ISSUE TITLE
Plugin didn't draw the map

### ISSUE THREAD

**Issue by TimChebotarev** [amdecker/obsidian-argdown-plugin#2]
I used the sample code from https://argdown.org/#_1-nested-lists-of-pros-cons

```
[Argdown is the best]: Argdown is the best tool for analyzing complex argumentation and creating argument maps.
	- <Editors easier>: Argument map editors are way easier to use. #pro-editor
		+ <WYSIWYG>: In argument map editors what you see during editing is what you get at the end: an argument map. #pro-editor
	+ <Pure Data>: With Argdown no user interface gets in your way. You can focus on writing without getting distracted.
```

After switching to Preview mode I don't see the map.

Chrome DevTools:
![image](https://user-images.githubusercontent.com/11838916/123998297-05e62980-d9da-11eb-8c8f-dff828def28c.png)

argdown-cli was installed by
`npm install -g @argdown/cli`

and I can run `argdown --version` it with console

![image](https://user-images.githubusercontent.com/11838916/123999230-f3202480-d9da-11eb-95f3-14429ac1a2b0.png)

System:
![image](https://user-images.githubusercontent.com/11838916/123999368-1d71e200-d9db-11eb-9a62-b1bce3119f24.png)

Obsidian version: 0.12.5

**Comment by amdecker** [comment]
It looks like you are using nvm and that prevented argdown from being installed in /usr/bin/local/

Can you install argdown without using NVM to the system location, or maybe try to link it? https://stackoverflow.com/questions/38485647/how-to-use-node-in-usr-local-bin-instead-of-the-one-in-nvm

I do not have easy access to a mac atm, so I will have a tough time debugging nvm issues on windows.

**Comment by dbyler** [comment]
Hmm, same issue here with a slightly different installation path. I used the recommended installation method from https://github.com/christianvoigt/argdown/tree/master/packages/argdown-cli , which was `npm install -g @argdown/cli`

This resulted in an installation at /opt/homebrew/bin/argdown

Linking to /usr/bin/local didn't work for me (`sudo ln -s /opt/homebrew/bin/argdown /usr/local/bin`)

**Comment by dbyler** [comment]
Excited to try this out though! Hope we can get it sorted

**Comment by amdecker** [comment]
I had an epiphany yesterday on how to solve a problem, so now I'm almost done with version 2.0 which bundles argdown with the plugin so no one will need to worry about installing anything extra.

 I wanted to let you know so that you don't go down a rabbit hole which won't be relevant in a few days.

It should be ready in the next few days!

**Comment by amdecker** [comment]
Updated the plugin!
