### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by trungng2006** [amdecker/obsidian-argdown-plugin#3]
Could you please add darkmode for the argdown canvas? :D

**Comment by trungng2006** [comment]
I resolved this by adding this snippet to my css:
```
:root
{
	--argdown-bg-color: #000000;
}

```

**Comment by amdecker** [comment]
Great thanks -- I added a link to this to the readme for others to find.

**Comment by beerws** [comment]
It will look a bit more neat if you use the primary color of Obsidians dark mode `#202020` (see: [Default Obsidian Theme Colors](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/Default+Obsidian+Theme+Colors))
```
:root
{
	--argdown-bg-color: #202020;
}
```
