### ISSUE TITLE
Groups not visualized

### ISSUE THREAD

**Issue by Coriakin** [amdecker/obsidian-argdown-plugin#6]
I just found this plugin, and I am so thankful, argument mapping is one of the greatest itches I have and now I can do it all within obsidian. Just amazing thank you!!!

I was testing it out and notice that perhaps the css or what not  do not render the groups correctly? Or perhaps this is not supported?

**Steps**
- Go to: https://argdown.org/guide/elements-of-an-argument-map.html
- Copy and paste the source from that into an argdown code block in obsidian

**Expectation**
To see the "I am a group" and "I am a subgroup" in hues of gray

**What I see**
None of the groups

**Environment**
- Obsidian 0.12.11
- Tried disabling themes in case that messed something up, but that did not affect it.

**Comment by amdecker** [comment]
Thanks for pointing that out! 

I released a new version that should fix it. Please update your plugin and try again.

**Comment by Coriakin** [comment]
Great that was a speedy fix it works now! Thank you! :)
