### ISSUE TITLE
Blocks with unicode characters are rendered misaligned

### ISSUE THREAD

**Issue by ooker777** [amdecker/obsidian-argdown-plugin#9]
```
```argdown
[Thesis]: Test
  +  Toán học là nghệ thuật đặt ra cùng một cái tên cho những thứ khác `nhau`
```

![](https://i.imgur.com/voV93Xs.png)

It isn't so in the [Argdown sandbox](https://argdown.org/sandbox/map/?argdown=%5BThesis%5D%3A%20Test%0A%20%20%2B%20To%C3%A1n%20h%E1%BB%8Dc%20l%C3%A0%20ngh%E1%BB%87%20thu%E1%BA%ADt%20%C4%91%E1%BA%B7t%20ra%20c%C3%B9ng%20m%E1%BB%99t%20c%C3%A1i%20t%C3%AAn%20cho%20nh%E1%BB%AFng%20th%E1%BB%A9%20kh%C3%A1c%20nhau)

**Comment by amdecker** [comment]
Hi thanks for reaching out. When I check the argdown sandbox it looks the same as it does in Obsidian.

![image](https://user-images.githubusercontent.com/20598318/157432233-7735a712-0264-4a9c-9981-60b5be581f63.png)

**Comment by ooker777** [comment]
Thanks, I open it in Argdown's repo [here](https://github.com/christianvoigt/argdown/issues/331). I think it might be a good idea for GitHub to support transferring issues between repo?

**Comment by ooker777** [comment]
It seems that Argdown also support Dagre graph. Is there a way to use that instead?
